# Generated by Django 3.1.3 on 2020-11-19 06:01

import akastories.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryUser',
            fields=[
                ('nim', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[1000, 1000], upload_to=akastories.models.story_file_name)),
                ('following', models.ManyToManyField(to='akastories.StoryUser')),
            ],
        ),
    ]
