# Generated by Django 3.1.3 on 2020-11-19 06:03

import akastories.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('akastories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyuser',
            name='story_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[1000, 1000], upload_to=akastories.models.story_file_name),
        ),
        migrations.AlterField(
            model_name='storyuser',
            name='following',
            field=models.ManyToManyField(blank=True, to='akastories.StoryUser'),
        ),
        migrations.AlterField(
            model_name='storyuser',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[500, 300], upload_to=akastories.models.profile_image_file_name),
        ),
    ]
